# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
cache: cocoapods
podfile: Example/Podfile
rvm: 1.9.3
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/netfox-Droar.xcworkspace -scheme netfox-Droar-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=4.0 | xcpretty
- set -o pipefail && xcodebuild -workspace Example/netfox-Droar.xcworkspace -scheme netfox-Droar-Example -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=3.2 | xcpretty
- pod lib lint
